name: Pipeline Frontend UI

on: 
  push: 
    branches:
      - release
  pull_request:
    branches:
      - release

jobs:

  build:

    runs-on: ubuntu-latest
    environment:
      name: prd

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Docker Hub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN_UI }}
        
    - name: Docker Image
      run: docker build -f Dockerfile -t ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPOSITORY_IU }}:v1 --no-cache .
            
    - name: Docker Push
      run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPOSITORY_IU }}:v1
            
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
