name: Pipeline Frontend UI

on:
  push:
    branches:
      - release
  pull_request:
    branches:
      - release

jobs:
  build:
    name: Build  
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Install
        run: npm install

      - name: Build
        run: npm run build
      
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: path artifact
          path: dist

  deploy:
    name: Deploy  
    runs-on: ubuntu-latest
    environment:
      name: prd
    needs: build
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ID }}
          aws-secret-access-key: ${{ secrets.AWS_KEY }}
          role-duration-seconds: 1200
          aws-region: us-east-1

      - name: Download artifact  
        uses: actions/download-artifact@v2
        with:
          name: path artifact
          path: dist

      - name: Deploying application to Amazon S3
#        uses: jakejarvis/s3-sync-action@master
#        with:
#          args: --acl public-read --follow-symlinks --delete
#        env:
#          AWS_S3_BUCKET: ${{ secrets.AWS_BUCKET }}
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ID }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_KEY }}
#          AWS_REGION: us-east-1
#          SOURCE_DIR: dist
        run: aws s3 cp --recursive s3://${{ secrets.AWS_BUCKET }} dist
        